name: otomad-prisma-main
version: "3.9"

services:
  postgres:
    image: postgres:15@sha256:e01f532a5983facbed9dc9df6b34aab4ede236fc40a288055050b334fb44fcc4
    ports:
      - target: 5432
        published: 35432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
